appName: trade-ui
development: true
log:
  config:
    level: debug
    disableCaller: true
    disableStacktrace: true
    encoding: json
    outputPaths:
      - stdout
#      - "logs/test.log"
    errorOutputPaths:
      - stderr
  rotate:
    maxSize: 1
    maxage: 1
    maxbackups: 1
    localtime: true
    compress: false
web:
  server:
    addr: 0.0.0.0:8080
  engine:
    routerGroups:
      - default:
          handleFuncs:
            - accessLog:
            - recovery:
quickfix:
  configFilePath: "etc/tradeclient.cfg"
